Arreglar l'actualització del token de les corves a l'OV
Som-Energia/openerp_som_addons pull request #196
Opened 2022-08-26 08:18 UTC by oriolpiera

## Objectiu
Arreglar l'actualització del token de les corves a l'OV

## Targeta on es demana o Incidència 
https://secure.helpscout.net/conversation/1947775472/12844715?folderId=3063411

## Comportament antic
Només s'actualitzava el token si el partner no en tenia prèviament

## Comportament nou
- S'actualitza el token també quan ja existeix (segon contracte de la titular).
- També s'actualitza en cas d'administradora
- Es deixa d'actualitzar per a pagadores i notificadores

## Comprovacions

- [ ] Hi ha testos
- [ ] Reiniciar serveis
- [ ] Actualitzar mòdul
- [ ] Script de migració
- [ ] Modifica traduccions

2024-05-31 11:08 UTC, vokimon commented
@oriolpiera aquest comportament era pretés. Ho vam canviar en aquesta PR #304 perque ens donava mooolts problemes e incidències.

El comportament nou seria que ERP només crea el token quan hi ha un vincle nou si es que no hi ha cap contracte. És la OV qui dispara l'actualitzacio dels contractes vinculats al token al mongo, quan la usuaria es logineja a la OV pero mantenint el mateix token. Es la forma més senzilla i menys error prone que vam trobar per reduir les incidencies (teniem una o dues cada setmana ara fa moolt que no en tenim). Tambe simplifica el testeig ja que tenim els mateixos tokens a testing i produccio i no tenim el problema que teniem perque haviem de generar un token diferent per testing. Ara es genera automaticament si no el troba.

També veig que has tret les relacions de notificacio i pagador (ara propietari del compte). No estic segur si s'escau.

Si es que heu trobat algun problema, parlem-ho.

2024-05-31 11:43 UTC, vokimon commented
Oriol, veig tambe que la branca no surt del master actual i el codi en el que es basa no te aquests canvis que faig mencio. Pensava que els havies elimitat, amb tot el que suposa. En tot cas, caldria fer un merge i sortirien tot de conflictes perque vaig reescriure el codi bastant.

2024-05-31 12:29 UTC, vokimon requested changes
The branch is old and does not take into account already integrated changes on the module from PR #304 which changes behaviour of the token regeneration. See the comments.

2024-06-03 05:17 UTC, oriolpiera commented
Tanco perquè hi ha una PR posterior que ho arregla, excepte el cas de la figura d'administradora de la pòlissa, però crec que aquesta figura no s'esta fent servir.
https://github.com/Som-Energia/openerp_som_addons/pull/304

2024-06-03 05:17 UTC, closed without merging