Noves vistes CAU
Som-Energia/openerp_som_addons pull request #367
Opened 2023-06-02 09:48 UTC by MarcCalvoC

## Objectiu

- Millorar les vistes dels contractes amb autoconsum

## Targeta on es demana o Incidència 

## Comportament antic

- N/A

## Comportament nou

- S'ha afegit una nova vista per els contractes amb autoconsum, i s'han afegit alguns camps als filtres

## Comprovacions

- [ ] Hi ha testos
- [x] Reiniciar serveis
- [ ] Actualitzar mòdul
- [x] Script de migració
- [ ] Modifica traduccions

2023-07-18 14:46 UTC, destanyol approved these changes

2023-07-18 14:46 UTC, destanyol commented on som_polissa/giscedata_polissa_view.xml
> +                    <field name="data_ultima_factura"/>
Aquest camp on es crea?

2023-07-18 14:50 UTC, destanyol requested changes

2023-07-18 14:50 UTC, destanyol commented on som_polissa/giscedata_polissa.py
> +        bat_pol_o = self.pool.get('giscedata.bateria.virtual.polissa')
Aquest mòdel té una dependència d'un altre mòdul que no està especificat al terp

2023-07-18 14:51 UTC, destanyol commented on som_polissa/giscedata_polissa.py
> +        bat_pol_o = self.pool.get('giscedata.bateria.virtual.polissa')
`giscedata_facturacio_bateria_virtual`

2023-08-01 09:54 UTC, destanyol commented on som_polissa/giscedata_polissa_view.xml
> +                    <field name="data_ultima_factura"/>
Aquest camp no hi és a Producció!

2023-08-01 10:09 UTC, MarcCalvoC commented on som_polissa/giscedata_polissa_view.xml
> +                    <field name="data_ultima_factura"/>
Et refereixes al camp 'data_ulitma_factura'?

2023-08-01 10:55 UTC, MarcCalvoC commented on som_polissa/giscedata_polissa_view.xml
> +                    <field name="data_ultima_factura"/>
:smile:

2023-08-08 13:02 UTC, merged

2023-09-01 08:13 UTC, oriolpiera commented on som_polissa/giscedata_polissa_view.xml
> +            <field name="priority" eval="1"/>
@MarcCalvoC faré una PR per baixar la prioritat d'aquesta vista, ja que passa per davant de la vista general de pòlissa.