New indexed prices
Som-Energia/openerp_som_addons pull request #552
Opened 2024-03-04 16:25 UTC by MariteSomEnergia

## Objectiu
Mostrar preus diaris de la indexada a la web de Somenergia

## Targeta on es demana o Incidència
https://trello.com/c/D5nCJmw2/5881-crida-de-lapi-que-retorni-la-taula-dels-preus-24h

## Comportament antic
No existia

## Comportament nou
S'han creat dues funcions:
- get_indexed_prices: per obtenir preus diaris de la indexeda 
- get_compensation_prices: per obtenir preus de compensació

## Comprovacions

- [X] Hi ha testos
- [ ] Reiniciar serveis
- [ ] Actualitzar mòdul
- [ ] Script de migració
- [ ] Modifica traduccions

2024-03-05 15:21 UTC, javikalsan reviewed
Yeah! :whale:  I read good abstraction strategies, failing as soon as possible and easy to read code. I need your help in order to setup locally the project and eventually review tests.

2024-03-05 15:21 UTC, javikalsan commented on som_polissa/exceptions/exceptions.py
> +class TariffNonExists(SomPolissaException):
Could be a typo at `Non` instead `Not`?

2024-03-05 15:21 UTC, javikalsan commented on www_som/som_indexada_webforms_helpers.py
> +from datetime import datetime, date, timedelta
Seems `date` is not used

2024-03-05 15:21 UTC, javikalsan commented on www_som/som_indexada_webforms_helpers.py
> +    def traceback_info(self, exception):
Seems `traceback_info` is already defined at `www_entry_point` decorator, I think I am missing some context here, let's talk about it :speaking_head:

2024-03-05 15:21 UTC, javikalsan commented on www_som/som_indexada_webforms_helpers.py
> +            curves = []
We can use a comprehension list here

2024-03-11 09:09 UTC, destanyol requested changes
Ha de passar el pre-commit.
En principi aplicant el diff del següent enllaç ja ho solucionareu:
https://github.com/Som-Energia/openerp_som_addons/actions/runs/8191002803/job/22399232171

No passa testos però en principi no és cosa vostra:
https://github.com/Som-Energia/openerp_som_addons/actions/runs/8191002802/job/22399232830

2024-03-12 11:33 UTC, MariteSomEnergia commented on www_som/som_indexada_webforms_helpers.py
> +            curves.append(prices_obj.read(cursor, uid, price_id, ['initial_price','maturity']))
done

2024-03-12 11:34 UTC, MariteSomEnergia commented on www_som/som_indexada_webforms_helpers.py
> +        price_ids = prices_obj.search(cursor, uid, params, order='hour_timestamp')
done

2024-03-12 11:57 UTC, MariteSomEnergia commented on www_som/som_indexada_webforms_helpers.py
> +        if first_date == None or last_date == None or \
Es necessari perquè es vol una excepció si alguna de les dues dates es None. He afegit un test per verificar-lo.

2024-03-12 12:37 UTC, destanyol approved these changes

2024-03-12 14:01 UTC, merged